language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: hsWeatiNyozsUsNdYcH6Zf3DTIx7ct3Ns0INb6mK35Xrjf1fIeYgo39BL6/i8CL81Ofw7MfomYsCc3y2nyDddAAix2OEWkHmmR56FwXQ5HZdPbxptQIjvOBSLt6QW9CPnq66NSGk9StS6BBIznrGaACIcjpPYImAGqdx0ZV1w744zDQr1oba+5o7P7cXqyN0GbGW3KV5KxMcKo799ppiz4IUFWCYtfq5uSWj/7WOtjhsAx9TnknBOA4gBVjkYtPtZ71pjuVxBGc1lbD4bVaJRcbKXkbGCdSWpYa8P7tOUAy7h9iGLZkEdleqVDtQB7Mjc0MD4LPU84M0cqE5G0vfmlEoAT0XZFmM361+5HPoqz7fcfKONq6IHfNM38ZGzJtAWrgGC6WKah6FnlSRd5HnjJHAv9rhMoLRjMpc+jDfb9DWvGPAfwUu8cSZSXBN+8ViDTyZG+fZVottfYXG73NsRpY/1dNBeJhPxyOfe17qf2Qwqj3tGBzdQVpUogGih/37EYOG6DuHMHshmWYsdTwqJollMp7P0XfyUs2+CO7TwXL/pdVFWhH+D0mwCLDyuvD4zxdrMy2gVmWIHeWwzfCERehMQ6eKTHUruxTVxFYvgMG9dpo5NaBOCMGnfQLdmIO2ll/VI4Hqs8D6SQaeoiOO1RYLYg0kEtCjQDKlbYA6cq0=
  app: evening-thicket-30478
  on:
    repo: sbschechner/commSoup-API
